modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="shulkerstone" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Shulker Stone" #mandatory
authors="Corrupted_Link" #optional
description='''
A minecraft mod that add a decorative block that looks like a shulker box and baseless end rods
'''

[[dependencies.shulkerstone]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.shulkerstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
